# main entry point for dotfiles

so() { [ -s $1 ] && source $1; }

so ~/.bash/profile                        # main configuration
so ~/.bash/prompt                         # 
so ~/.bash/aliases                        #
so ~/.bash/functions                      #
so ~/.bash/path                           #
so ~/.bash/dotfilesrc                     # git-dotfiles specific stuff
