# Download plugins
plugins_dir="${HOME}/.zsh-plugins"
if [[ ! -e ${plugins_dir}/zsh-syntax-highlighting ]]; then
  git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ${plugins_dir}/zsh-syntax-highlighting
fi
if [[ ! -e ${plugins_dir}/zsh-autosuggestions ]]; then
  git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git ${plugins_dir}/zsh-autosuggestions
fi
if [[ ! -e ${plugins_dir}/powerlevel10k ]]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${plugins_dir}/powerlevel10k
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -Uz compinit
compinit

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# mise-en-place
eval "$(mise activate zsh)"

# gpg
export GPG_TTY=$TTY

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='cot -w'
fi

# Shortcuts
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias dev="cd ~/Documents/dev"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"

alias cat="bat --theme=TwoDark"
alias ls="eza --git --color=always --group-directories-first"
alias tree="eza --tree --level=2"

alias xcdd='rm -rf ~/Library/Developer/Xcode/DerivedData/*'
alias simulator='open "$(xcode-select -p)/Applications/Simulator.app"'

function xc {
  local xcode_files
  xcode_files=(${1:-.}/{*.{xcworkspace,xcodeproj,swiftpm},Package.swift}(N))

  if [[ ${#xcode_files} -eq 0 ]]; then
    echo "No Xcode files found in ${1:-the current directory}." >&2
    return 1
  fi

  local active_path
  active_path=${"$(xcode-select -p)"%%/Contents/Developer*}
  echo "Found ${xcode_files[1]}. Opening with ${active_path}"
  open -a "$active_path" "${xcode_files[1]}"
}

# Key bindings
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Activate plugins
source ${plugins_dir}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ${plugins_dir}/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${plugins_dir}/powerlevel10k/powerlevel10k.zsh-theme
eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
